services:

    shapecode_twig_namespace.locator.templating_locator:
        class: "%templating.locator.class%"
        arguments:
            - '@shapecode_twig_namespace.locator.chain_file_locator'
            - '%kernel.cache_dir%'

    shapecode_twig_namespace.locator.chain_file_locator:
        class: Shapecode\Bundle\TwigNamespacePathsBundle\Locator\ChainFileLocator

    shapecode_twig_namespace.locator.templates_dir_file_locator:
        class: Shapecode\Bundle\TwigNamespacePathsBundle\Locator\TemplatesDirectoryFileLocator
        arguments:
            - '@kernel'
        tags:
            - { name: shapecode.template_file_locator }